# Schema for the configuration files of the User module.

reservations.settings:
  type: config_object
  label: 'Reservation settings'
  mapping:
    anonymous:
      type: label
      label: 'Name'
    verify_mail:
      type: boolean
      label: 'Require email verification when a visitor creates a reservation'
    notify:
      type: mapping
      label: 'Notify user'
      mapping:
        checkout_confirm:
          type: boolean
          label: 'Confirm the reservation'
    register:
      type: string
      label: 'Who can register accounts?'
    cancel_method:
      type: string
      label: 'When cancelling a user account'

reservation.mail:
 type: config_object
 label: 'Email settings'
 mapping:
  cancel_confirm:
    type: mail
    label: 'Reservation cancellation confirmation'
  reservation_admin_created:
    type: mail
    label: 'Reservation created by administrator'
  reservation_no_approval_required:
    type: mail
    label: 'Reservation confirmation (No approval required)'
  reservation_pending_approval:
    type: mail
    label: 'Registration confirmation (Pending approval)'
  reservation_pending_approval_admin:
    type: mail
    label: 'Admin (user awaiting approval)'
  status_canceled:
    type: mail
    label: 'Reservation cancelled'

reservations.season.*:
  type: config_entity
  label: 'Season settings'
  mapping:
    year:
      type: string
      label: 'Season year'
    start_date:
      type: string
      label: 'The date of the first day of the season'
    end_date:
      type: string
      label: 'The date of the last day of the season'
    opening_date:
      type: string
      label: 'The opening date of the reservations'
    prices:
      type: mapping
      label: 'Prices, specific to the season'
      mapping:
        1_soleil:
          type: integer
          label: '1 soleil price'
        2_soleil:
          type: integer
          label: '2 soleil price'
        3_soleil:
          type: integer
          label: '3 soleil price'


#field.formatter.settings.user_name:
#  type: mapping
#  mapping:
#    link_to_entity:
#      type: boolean
#      label: 'Link to the user'




